name: slim_conservation
channels:
  - pytorch
  - bioconda
  - conda-forge
dependencies:
  - alv=1.7.2=pyhdfd78af_0
  - amply=0.1.6=pyhd8ed1ab_0
  - anyio=4.2.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h02f2b3b_4
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - biopython=1.82=py312he37b823_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py312h9f69965_1
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2024.6.2=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.6.2=pyhd8ed1ab_0
  - cffi=1.16.0=py312h8e38eb3_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - coin-or-cbc=2.10.10=hfaca913_0
  - coin-or-cgl=0.60.7=hf050ae7_0
  - coin-or-clp=1.17.8=h65c2c7c_0
  - coin-or-osi=0.108.8=h19bcb3e_0
  - coin-or-utils=2.11.9=h12587b1_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - conda-inject=1.3.1=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.2.0=py312h76e736e_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - datrie=0.8.2=py312h02f2b3b_7
  - debugpy=1.8.0=py312h9f69965_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.20.1=py312h81bd7bf_3
  - dpath=2.1.6=pyha770c72_0
  - eido=0.2.2=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.15.4=pyhd8ed1ab_0
  - fonttools=4.47.0=py312he37b823_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.1.5=py312hfa9fade_1
  - humanfriendly=10.0=pyhd8ed1ab_6
  - idna=3.6=pyhd8ed1ab_0
  - immutables=0.20=py312h02f2b3b_1
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.28.0=pyh3cd1d5f_0
  - ipython=8.19.0=pyh707e725_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.4=py312h81bd7bf_3
  - jsonschema=4.20.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.20.0=pyhd8ed1ab_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter-lsp=2.2.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.0=py312h81bd7bf_0
  - jupyter_events=0.9.0=pyhd8ed1ab_0
  - jupyter_server=2.12.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.1=pyhd8ed1ab_0
  - jupyterlab=4.0.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.25.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py312h389731b_1
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=20_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=20_osxarm64_openblas
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=20_osxarm64_openblas
  - liblapacke=3.9.0=20_osxarm64_openblas
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libpng=1.6.39=h76d750c_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.44.2=h091b4b1_0
  - libtiff=4.6.0=ha8a6c65_2
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=17.0.6=hcd81f8e_0
  - logmuse=0.2.6=pyh8c360ce_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py312h02f2b3b_1
  - matplotlib=3.8.2=py312h1f38498_0
  - matplotlib-base=3.8.2=py312hba9b818_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.1=h41d338b_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.0.7=py_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.14.0=pyhd8ed1ab_0
  - nbconvert-core=7.14.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.14.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h463b476_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - notebook=7.0.6=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numpy=1.26.3=py312h8442bc7_0
  - openjpeg=2.5.0=h4c1507b_3
  - openpyxl=3.1.2=py312h02f2b3b_1
  - openssl=3.3.1=hfb2fe0b_1
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.4=py312h9e53831_0
  - pandoc=3.1.3=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - peppy=0.40.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py312hac22aec_0
  - pip=23.3.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.2=pyhd8ed1ab_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - prometheus_client=0.19.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - psutil=5.9.7=py312he37b823_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.7.0=py312h81bd7bf_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyobjc-core=10.1=py312h9d22092_0
  - pyobjc-framework-cocoa=10.1=py312h9d22092_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyprojroot=0.3.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.4=pyhd8ed1ab_0
  - python=3.12.1=hdf0ec26_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=1.0.0=pyhd8ed1ab_1
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.4=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytorch=2.2.2=py3.12_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h02f2b3b_1
  - pyzmq=25.1.2=py312h1edf716_0
  - qtconsole-base=5.5.1=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - readline=8.2=h92ec313_1
  - referencing=0.32.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.7.0=pyhd8ed1ab_0
  - rpds-py=0.16.2=py312h5280bc4_0
  - scikit-learn=1.5.1=py312h1b546db_0
  - scipy=1.11.4=py312h510ce61_0
  - seaborn=0.13.1=hd8ed1ab_0
  - seaborn-base=0.13.1=pyhd8ed1ab_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - slack-sdk=3.26.2=pyha770c72_0
  - slack_sdk=3.26.2=hd8ed1ab_0
  - smart_open=6.4.0=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snakemake=8.1.0=hdfd78af_0
  - snakemake-interface-common=1.15.0=pyhdfd78af_1
  - snakemake-interface-executor-plugins=8.1.3=pyhdfd78af_0
  - snakemake-interface-storage-plugins=3.0.0=pyhdfd78af_0
  - snakemake-minimal=8.1.0=pyhdfd78af_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py312hf635c46_0
  - stopit=1.1.2=py_0
  - sympy=1.12.1=pypyh2585a3b_103
  - tabulate=0.9.0=pyhd8ed1ab_1
  - terminado=0.18.0=pyh31c8845_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.10=pyhd8ed1ab_0
  - torchvision=0.17.2=py312_cpu
  - tornado=6.3.3=py312h02f2b3b_1
  - traitlets=5.14.1=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.20240106=pyhd8ed1ab_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023d=h0c530f3_0
  - ubiquerg=0.6.3=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - wrapt=1.16.0=py312he37b823_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yte=1.5.4=pyha770c72_0
  - zeromq=4.3.5=h965bd2d_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - alfpy==1.0.6
      - fair-esm==2.0.0
      - fsspec==2024.6.1
      - huggingface-hub==0.23.4
      - local-conservation-pipeline==0.1
      - logomaker==0.8
      - regex==2024.5.15
      - safetensors==0.4.3
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - transformers==4.42.3
